import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import web3 from 'web3';
import {FormEvent, useState} from "react";
import {useRouter} from 'next/router'

const Home: NextPage = () => {
    const router = useRouter();
    const [address, setAddress] = useState('');

    const handleOnSubmit = (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        if (!web3.utils.isAddress(address)) {
            alert('Not a avalid address');
        } else {
            router.push('/nft/' + address);
        }
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <Link href="/">TangleRarity!</Link>
                </h1>

                <div className={styles.description}>
                    <form onSubmit={handleOnSubmit}>
                        <label htmlFor="address">Address</label>
                        <input id="address" type="text" autoComplete="address" required
                               onChange={e => setAddress(e.currentTarget.value)} value={address} />
                        <button type="submit">Calculate</button>
                    </form>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
