import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import web3 from 'web3';
import {FormEvent, useState} from "react";
import {useRouter} from 'next/router';
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import Box from '@mui/material/Box';

const Home: NextPage = () => {
    const router = useRouter();
    const [address, setAddress] = useState('');

    const handleOnSubmit = (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        if (!web3.utils.isAddress(address)) {
            alert('Not a avalid address');
        } else {
            router.push('/nfts/' + address);
        }
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <Link href="/">TangleRarity!</Link>
                </h1>

                <Box>
                    <TextField id="outlined-basic" label="Outlined" variant="outlined" />
                    <Button variant='contained'>Submit</Button>
                </Box>

                <div className={styles.description}>
                    <form onSubmit={handleOnSubmit}>
                        <label htmlFor="address">Address</label>
                        <input id="address" type="text" autoComplete="address" required
                               onChange={e => setAddress(e.currentTarget.value)} value={address} />
                        <Button variant='contained'>Submit</Button>
                    </form>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://github.com/boxcee/tanglerarity"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    <span className={styles.logo}>
                        <Image src="/github.svg" alt="Github Logo" width={32} height={32} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home;
