name: ci

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ github.repository }}:latest"

  deploy:
    runs-on: ubuntu-latest

    needs:
    - publish

    steps:
      - name: Deploy New Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /tanglerarity
            docker-compose -p tanglerarity up -d --build --force-recreate tanglerarity
